# Generated by Django 6.1 on 2026-08-19 22:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.constraints
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento/Provincia')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('PROPIETARIO', 'Propietario'), ('INQUILINO', 'Inquilino')], default='PROPIETARIO', max_length=20, verbose_name='Tipo de usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('codigo_referencia', models.CharField(max_length=20, unique=True, verbose_name='Código de referencia')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('DPTO', 'Departamento'), ('LOCAL', 'Local Comercial'), ('OFIC', 'Oficina'), ('OTRO', 'Otro')], max_length=10, verbose_name='Tipo')),
                ('habitaciones', models.PositiveIntegerField(default=0, verbose_name='Habitaciones')),
                ('banos', models.PositiveIntegerField(default=0, verbose_name='Baños')),
                ('area_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área construida (m²)')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio mensual (Gs)')),
                ('deposito_garantia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Depósito de garantía (Gs)')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='inmuebles/fotos/', verbose_name='Foto principal')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmuebles', to='alquiler.ciudad')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmuebles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'ordering': ['codigo_referencia'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Gs)')),
                ('fecha', models.DateField(verbose_name='Fecha del gasto')),
                ('categoria', models.CharField(choices=[('REP', 'Reparación'), ('IMP', 'Impuesto'), ('SERV', 'Servicios (agua/luz)'), ('OTRO', 'Otro')], max_length=5, verbose_name='Categoría')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos/', verbose_name='Comprobante')),
                ('pagado', models.BooleanField(default=True, verbose_name='¿Pagado?')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='alquiler.inmueble')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ContratoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número de contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto mensual (Gs)')),
                ('deposito', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Depósito (Gs)')),
                ('periodicidad', models.CharField(choices=[('MEN', 'Mensual'), ('TRI', 'Trimestral'), ('ANU', 'Anual')], default='MEN', max_length=3, verbose_name='Periodicidad')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('FIN', 'Finalizado'), ('RES', 'Rescindido'), ('REN', 'Renovado')], default='ACT', max_length=3, verbose_name='Estado')),
                ('documento_contrato', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Documento del contrato (PDF)')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='alquiler.inmueble')),
            ],
            options={
                'verbose_name': 'Contrato de alquiler',
                'verbose_name_plural': 'Contratos de alquiler',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('NIE', 'NIE'), ('PAS', 'Pasaporte')], max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono_principal', models.CharField(max_length=20, verbose_name='Teléfono principal')),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono secundario')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
                'ordering': ['apellido', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='inquilino_documento_unico')],
            },
        ),
        migrations.CreateModel(
            name='ContratoInquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('TIT', 'Titular'), ('COD', 'Codeudor'), ('FIA', 'Fiador/Garante')], default='TIT', max_length=3, verbose_name='Rol')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_inquilinos', to='alquiler.contratoalquiler')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_inquilinos', to='alquiler.inquilino')),
            ],
            options={
                'verbose_name': 'Inquilino de contrato',
                'verbose_name_plural': 'Inquilinos de contrato',
            },
        ),
        migrations.AddField(
            model_name='contratoalquiler',
            name='inquilinos',
            field=models.ManyToManyField(related_name='contratos', through='alquiler.ContratoInquilino', to='alquiler.inquilino'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('fecha_periodo', models.DateField(verbose_name='Fecha del período (mes al que corresponde)')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Gs)')),
                ('metodo_pago', models.CharField(choices=[('EFEC', 'Efectivo'), ('TRANS', 'Transferencia'), ('TARJ', 'Tarjeta'), ('CHEQ', 'Cheque')], max_length=10, verbose_name='Método de pago')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('PAG', 'Pagado'), ('PEN', 'Pendiente'), ('ANU', 'Anulado')], default='PEN', max_length=3, verbose_name='Estado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='alquiler.contratoalquiler')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddConstraint(
            model_name='inmueble',
            constraint=models.CheckConstraint(condition=models.Q(('precio_mensual__gt', 0)), name='inmueble_precio_mensual_positivo'),
        ),
        migrations.AddConstraint(
            model_name='gasto',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='gasto_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='contratoinquilino',
            constraint=models.UniqueConstraint(fields=('contrato', 'inquilino'), name='contrato_inquilino_unico'),
        ),
        migrations.AddConstraint(
            model_name='contratoalquiler',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='contrato_fecha_fin_posterior'),
        ),
        migrations.AddConstraint(
            model_name='contratoalquiler',
            constraint=models.CheckConstraint(condition=models.Q(('monto_mensual__gt', 0)), name='contrato_monto_mensual_positivo'),
        ),
        migrations.AddConstraint(
            model_name='contratoalquiler',
            constraint=models.CheckConstraint(condition=models.Q(('deposito__gte', 0)), name='contrato_deposito_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='contratoalquiler',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('estado', 'ACT')), expressions=[(models.Func('fecha_inicio', 'fecha_fin', function='daterange'), '&&'), ('inmueble', '=')], name='contrato_sin_solapamiento_por_inmueble'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(fields=('contrato', 'fecha_periodo'), name='pago_periodo_unico_por_contrato'),
        ),
    ]
