# Generated by Django 6.1 on 2026-08-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_alter_contratoalquiler_deposito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='recibo_pdf',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='recibos/', verbose_name='Recibo (PDF)'),
        ),
    ]
