# Generated by Django 6.1 on 2026-08-20 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_pago_recibo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquilinos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquilino_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
