# Generated by Django 6.1 on 2026-08-22 23:47

import alquiler.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_inquilino_registrado_por_inquilino_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoalquiler',
            name='documento_contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), alquiler.validators.ValidarTamanoArchivo(10)], verbose_name='Documento del contrato (PDF)'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='gastos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), alquiler.validators.ValidarTamanoArchivo(5)], verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='disponible',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/fotos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), alquiler.validators.ValidarTamanoArchivo(5)], verbose_name='Foto principal'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), alquiler.validators.ValidarTamanoArchivo(5)], verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(db_index=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_periodo',
            field=models.DateField(db_index=True, verbose_name='Fecha del período (mes al que corresponde)'),
        ),
    ]
