# Generated by Django 6.1 on 2026-08-23 14:15

import alquiler.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0005_alter_contratoalquiler_documento_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='documento_archivo',
            field=models.FileField(blank=True, null=True, upload_to='inquilinos/documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), alquiler.validators.ValidarTamanoArchivo(5)], verbose_name='Documento de identidad (PDF o imagen)'),
        ),
    ]
