# Generated by Django 6.1 on 2026-08-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0006_inquilino_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='documento_identidad',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula/RUC'),
        ),
    ]
